package com.example.ui.screens.profile

data class AnimeAvatar(
    val id: Int,
    val name: String,
    val anime: String,
    val category: String,
    val imageUrl: String
)

object AnimeAvatarRepository {
    val categories = listOf(
        "All",
        "Shonen",
        "Jujutsu Kaisen",
        "One Piece",
        "Naruto",
        "Demon Slayer",
        "Attack on Titan",
        "Bleach",
        "Dragon Ball",
        "Hunter x Hunter",
        "My Hero Academia",
        "Chainsaw Man",
        "Classics & Others"
    )

    val avatars = listOf(
        AnimeAvatar(1, "Levi", "Attack on Titan", "Attack on Titan", "https://s4.anilist.co/file/anilistcdn/character/large/b45627-CR68RyZmddGG.png"),
        AnimeAvatar(2, "Satoru Gojo", "Jujutsu Kaisen", "Jujutsu Kaisen", "https://s4.anilist.co/file/anilistcdn/character/large/b127691-9zqh1xpIubn7.png"),
        AnimeAvatar(3, "Killua Zoldyck", "Hunter x Hunter", "Hunter x Hunter", "https://s4.anilist.co/file/anilistcdn/character/large/b27-Z5O02kQUydpT.jpg"),
        AnimeAvatar(4, "Monkey D. Luffy", "One Piece", "One Piece", "https://s4.anilist.co/file/anilistcdn/character/large/b40-MNypXsxSRb1R.png"),
        AnimeAvatar(5, "Eren Yeager", "Attack on Titan", "Attack on Titan", "https://s4.anilist.co/file/anilistcdn/character/large/b40882-dsj7IP943WFF.jpg"),
        AnimeAvatar(6, "L Lawliet", "Death Note", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b71-1W4panC53vfs.png"),
        AnimeAvatar(7, "Lelouch Lamperouge", "Code Geass", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b417-gVLmIJu9phcK.png"),
        AnimeAvatar(8, "Roronoa Zoro", "One Piece", "One Piece", "https://s4.anilist.co/file/anilistcdn/character/large/b62-S7oAeA9WInjV.png"),
        AnimeAvatar(9, "Mikasa Ackerman", "Attack on Titan", "Attack on Titan", "https://s4.anilist.co/file/anilistcdn/character/large/b40881-F3gr1PkreDvj.png"),
        AnimeAvatar(10, "Emilia", "Re:Zero", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b88572-IzTwXEHSobRs.jpg"),
        AnimeAvatar(11, "Ken Kaneki", "Tokyo Ghoul", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b87275-mb13EWZBdbh3.png"),
        AnimeAvatar(12, "Arataka Reigen", "Mob Psycho 100", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b89334-OPj1hCzvrt7X.png"),
        AnimeAvatar(13, "Guts", "Berserk", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b422-XTaiTuvRohsV.png"),
        AnimeAvatar(14, "Itachi Uchiha", "Naruto", "Naruto", "https://s4.anilist.co/file/anilistcdn/character/large/b14-9Kb1E5oel1ke.png"),
        AnimeAvatar(15, "Kurisu Makise", "Steins;Gate", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b34470-Jw2LXZBL5R8i.png"),
        AnimeAvatar(16, "Makima", "Chainsaw Man", "Chainsaw Man", "https://s4.anilist.co/file/anilistcdn/character/large/b137080-UHcynYNjb5ZU.png"),
        AnimeAvatar(17, "Thorfinn Karlsefni", "Vinland Saga", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b10138-zOPrka0ddZOR.png"),
        AnimeAvatar(18, "Yuji Itadori", "Jujutsu Kaisen", "Jujutsu Kaisen", "https://s4.anilist.co/file/anilistcdn/character/large/b127212-FVm2tD0erQ5B.png"),
        AnimeAvatar(19, "Kakashi Hatake", "Naruto", "Naruto", "https://s4.anilist.co/file/anilistcdn/character/large/b85-mkVBh2yjxjmx.png"),
        AnimeAvatar(20, "Mai Sakurajima", "Rascal Does Not Dream of Bunny Girl Senpai", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b127222-Jh5hhP7vZ7s1.png"),
        AnimeAvatar(21, "Frieren", "Frieren", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b176754-PCnpqIOkjhFk.png"),
        AnimeAvatar(22, "Maomao", "The Apothecary Diaries", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b126824-MqsCncTO1qpv.png"),
        AnimeAvatar(23, "Kurapika", "Hunter x Hunter", "Hunter x Hunter", "https://s4.anilist.co/file/anilistcdn/character/large/b28-ivA7UGnfE40a.png"),
        AnimeAvatar(24, "Light Yagami", "Death Note", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b80-26EhwSsSqQ50.png"),
        AnimeAvatar(25, "Rintaro Okabe", "Steins;Gate", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b35252-DY9TW6pusqeh.png"),
        AnimeAvatar(26, "Kaguya Shinomiya", "Kaguya-sama", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b120649-NPaWaIpWy60E.png"),
        AnimeAvatar(27, "Denji", "Chainsaw Man", "Chainsaw Man", "https://s4.anilist.co/file/anilistcdn/character/large/b130102-FO1VHNnEnLlB.png"),
        AnimeAvatar(28, "Violet Evergarden", "Violet Evergarden", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b90169-4wr1Zehnsac8.png"),
        AnimeAvatar(29, "Shigeo Kageyama (Mob)", "Mob Psycho 100", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b89616-dXmdOc7L6SDi.png"),
        AnimeAvatar(30, "Power", "Chainsaw Man", "Chainsaw Man", "https://s4.anilist.co/file/anilistcdn/character/large/b137079-6yLEUYR3bmpr.png"),
        AnimeAvatar(31, "Edward Elric", "Fullmetal Alchemist", "Shonen", "https://s4.anilist.co/file/anilistcdn/character/large/b11-TA5Nuk7EDUZG.jpg"),
        AnimeAvatar(32, "Naruto Uzumaki", "Naruto", "Naruto", "https://s4.anilist.co/file/anilistcdn/character/large/b17-phjcWCkRuIhu.png"),
        AnimeAvatar(33, "Tanjiro Kamado", "Demon Slayer", "Demon Slayer", "https://s4.anilist.co/file/anilistcdn/character/large/b126071-BTNEc1nRIv68.png"),
        AnimeAvatar(34, "Shoto Todoroki", "My Hero Academia", "My Hero Academia", "https://s4.anilist.co/file/anilistcdn/character/large/b89220-KNBwaVFAR8FD.png"),
        AnimeAvatar(35, "Megumi Fushiguro", "Jujutsu Kaisen", "Jujutsu Kaisen", "https://s4.anilist.co/file/anilistcdn/character/large/b126635-L0y3I92JSUkN.png"),
        AnimeAvatar(36, "Katsuki Bakugo", "My Hero Academia", "My Hero Academia", "https://s4.anilist.co/file/anilistcdn/character/large/b88892-bdOha3lNcaN6.png"),
        AnimeAvatar(37, "Sakura Matou", "Fate", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b500-NQrLbnBr1sDv.png"),
        AnimeAvatar(38, "Osamu Dazai", "Bungo Stray Dogs", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b89198-qKmRTw4Y3PRC.png"),
        AnimeAvatar(39, "Joseph Joestar", "JoJo's Bizarre Adventure", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b6356-RImEfUfHpC58.png"),
        AnimeAvatar(40, "Megumin", "KonoSuba", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b89361-tq8PQQ4MmF0M.png"),
        AnimeAvatar(41, "Marin Kitagawa", "Darling in the FranXX", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b133676-kV2czE3C8Qls.png"),
        AnimeAvatar(42, "Rem", "Re:Zero", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b88575-Ayu8UPDA8NS6.png"),
        AnimeAvatar(43, "Chika Fujiwara", "Kaguya-sama", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b121103-UGLxT8utLPnq.png"),
        AnimeAvatar(44, "Askeladd", "Vinland Saga", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b13020-ZdiYlNmpRUNS.png"),
        AnimeAvatar(45, "Gon Freecss", "Hunter x Hunter", "Hunter x Hunter", "https://s4.anilist.co/file/anilistcdn/character/large/b30-lyFExKyDhefc.jpg"),
        AnimeAvatar(46, "Gintoki Sakata", "Gintama", "Shonen", "https://s4.anilist.co/file/anilistcdn/character/large/b672-cP5VPriN67xJ.png"),
        AnimeAvatar(47, "Nezuko Kamado", "Demon Slayer", "Demon Slayer", "https://s4.anilist.co/file/anilistcdn/character/large/b127518-NRlq1CQ1v1ro.png"),
        AnimeAvatar(48, "Kiyotaka Ayanokouji", "Classroom of the Elite", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b123212-ewZgUQr9vvEM.png"),
        AnimeAvatar(49, "Senkuu Ishigami", "Dr. STONE", "Shonen", "https://s4.anilist.co/file/anilistcdn/character/large/b124142-XUO1g7wRqkaT.png"),
        AnimeAvatar(50, "Zero Two", "Darling in the FranXX", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b124381-2gAVq76HPfL2.png"),
        AnimeAvatar(51, "Ichigo", "Darling in the FranXX", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b124382-bSBkjtYjJQtr.png"),
        AnimeAvatar(52, "Itsuki Nakano", "The Quintessential Quintuplets", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b126375-dEe9IyQ9By09.png"),
        AnimeAvatar(53, "Saitama", "One Punch Man", "Shonen", "https://s4.anilist.co/file/anilistcdn/character/large/b73935-ON5d0mAcrItd.jpg"),
        AnimeAvatar(54, "Armin Arlert", "Attack on Titan", "Attack on Titan", "https://s4.anilist.co/file/anilistcdn/character/large/b46494-g7xYYuBtYPnO.png"),
        AnimeAvatar(55, "Shouyou Hinata", "Haikyu!!", "Shonen", "https://s4.anilist.co/file/anilistcdn/character/large/b64769-WoWlCMLLgJ14.png"),
        AnimeAvatar(56, "Inosuke Hashibira", "Demon Slayer", "Demon Slayer", "https://s4.anilist.co/file/anilistcdn/character/large/n129130-SJC0Kn1DU39E.jpg"),
        AnimeAvatar(57, "Hisoka Morow", "Hunter x Hunter", "Hunter x Hunter", "https://s4.anilist.co/file/anilistcdn/character/large/b31-FZckOuu7L1un.png"),
        AnimeAvatar(58, "Kusuo Saiki", "Assassination Classroom Second Season", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b90107-ZULW5HlPX1uU.png"),
        AnimeAvatar(59, "Izuku Midoriya", "My Hero Academia", "My Hero Academia", "https://s4.anilist.co/file/anilistcdn/character/large/b89028-8w1I9o1ISHMg.png"),
        AnimeAvatar(60, "Izumi Miyamura", "Horimiya", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b66173-g8eU1LGWPB8O.png"),
        AnimeAvatar(61, "Subaru Natsuki", "Re:Zero", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b88573-F8yMTK9GhnTA.png"),
        AnimeAvatar(62, "Miko Iino", "Kaguya-sama", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b125886-TQbmqAaSgBLS.png"),
        AnimeAvatar(63, "Sung Jin-Woo", "Solo Leveling", "Shonen", "https://s4.anilist.co/file/anilistcdn/character/large/b129928-BCEjVaP0AQSw.png"),
        AnimeAvatar(64, "Hange Zoe", "Attack on Titan", "Attack on Titan", "https://s4.anilist.co/file/anilistcdn/character/large/b71121-7R7CnQd3lHgt.png"),
        AnimeAvatar(65, "Yuu Ishigami", "Kaguya-sama", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b121102-tiQFxnSEIAwm.png"),
        AnimeAvatar(66, "Sanji", "One Piece", "One Piece", "https://s4.anilist.co/file/anilistcdn/character/large/b305-6lisPmHtCnLT.png"),
        AnimeAvatar(67, "Zenitsu Agatsuma", "Demon Slayer", "Demon Slayer", "https://s4.anilist.co/file/anilistcdn/character/large/b129131-FZrQ7lSlxmEr.png"),
        AnimeAvatar(68, "Hitagi Senjougahara", "Bakemonogatari", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b22037-sY7GWSKYr2Nl.jpg"),
        AnimeAvatar(69, "Asuka Langley Souryuu", "Neon Genesis Evangelion", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b94-d631a3Z2KPvd.png"),
        AnimeAvatar(70, "Roy Mustang", "Fullmetal Alchemist", "Shonen", "https://s4.anilist.co/file/anilistcdn/character/large/b68-moBLY2WO2am3.png"),
        AnimeAvatar(71, "Aki Hayakawa", "Chainsaw Man", "Chainsaw Man", "https://s4.anilist.co/file/anilistcdn/character/large/b137081-TSrUR3mUJL6r.png"),
        AnimeAvatar(72, "Jotaro Kujo", "JoJo's Bizarre Adventure", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b4003-gWDSEGbeOAll.png"),
        AnimeAvatar(73, "Spike Spiegel", "Cowboy Bebop", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b1-ChxaldmieFlQ.png"),
        AnimeAvatar(74, "Ichigo Kurosaki", "Bleach", "Bleach", "https://s4.anilist.co/file/anilistcdn/character/large/b5-a7bkJgjhhigE.png"),
        AnimeAvatar(75, "Nico Robin", "One Piece", "One Piece", "https://s4.anilist.co/file/anilistcdn/character/large/b61-ywXUyyocEEqt.png"),
        AnimeAvatar(76, "Yor Forger", "SPY x FAMILY", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b138102-ZOAu9jI2d5ke.png"),
        AnimeAvatar(77, "Nobara Kugisaki", "Jujutsu Kaisen", "Jujutsu Kaisen", "https://s4.anilist.co/file/anilistcdn/character/large/b133700-f6sOO3TcgLV6.png"),
        AnimeAvatar(78, "Tobio Kageyama", "Haikyu!!", "Shonen", "https://s4.anilist.co/file/anilistcdn/character/large/b64771-BuCVs7B8bBdh.png"),
        AnimeAvatar(79, "Shinobu Oshino", "Bakemonogatari", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b23602-Z4MDNYcoAWZu.png"),
        AnimeAvatar(80, "Kento Nanami", "Jujutsu Kaisen", "Jujutsu Kaisen", "https://s4.anilist.co/file/anilistcdn/character/large/b133704-8wLTGjc234q2.png"),
        AnimeAvatar(81, "Sasuke Uchiha", "Naruto", "Naruto", "https://s4.anilist.co/file/anilistcdn/character/large/b13-SISLEw1oAD7a.png"),
        AnimeAvatar(82, "Rimuru Tempest", "That Time I Got Reincarnated as a Slime", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b123962-eL9yGV0NLMF7.png"),
        AnimeAvatar(83, "Yato", "Noragami", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b84677-PFmohzIXD1ud.png"),
        AnimeAvatar(84, "Giyu Tomioka", "Demon Slayer", "Demon Slayer", "https://s4.anilist.co/file/anilistcdn/character/large/b130050-qsLThJs5VIbz.png"),
        AnimeAvatar(85, "Erwin Smith", "Attack on Titan", "Attack on Titan", "https://s4.anilist.co/file/anilistcdn/character/large/b46496-Mu86MENd5wNB.png"),
        AnimeAvatar(86, "Maki Zenin", "Jujutsu Kaisen", "Jujutsu Kaisen", "https://s4.anilist.co/file/anilistcdn/character/large/b134167-5TCytk45YByD.png"),
        AnimeAvatar(87, "Anya Forger", "SPY x FAMILY", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b138100-4Li0tWRCa5bQ.png"),
        AnimeAvatar(88, "Rin Toosaka", "Fate", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b498-lwawtSpLyATL.png"),
        AnimeAvatar(89, "Hachiman Hikigaya", "My Teen Romantic Comedy SNAFU", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b67065-Dhec6tE2yWA9.png"),
        AnimeAvatar(90, "Koyomi Araragi", "Bakemonogatari", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b22036-Ed3CjwPlDLp4.png"),
        AnimeAvatar(91, "Ryomen Sukuna", "Jujutsu Kaisen", "Jujutsu Kaisen", "https://s4.anilist.co/file/anilistcdn/character/large/b133701-rCQuDpHr3UZL.png"),
        AnimeAvatar(92, "Artoria Pendragon", "Fate", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b497-Yg5pNmC8kxzs.png"),
        AnimeAvatar(93, "Shouko Nishimiya", "A Silent Voice", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b80243-RzxE51iUU5eq.png"),
        AnimeAvatar(94, "Homura Akemi", "Puella Magi Madoka Magica", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b38005-T3NR8p2f021x.jpg"),
        AnimeAvatar(95, "Kyoko Hori", "Horimiya", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b66171-o2vk3689wWFK.png"),
        AnimeAvatar(96, "Miku Nakano", "The Quintessential Quintuplets", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b126373-CWeyXb822uDN.png"),
        AnimeAvatar(97, "Hitori Gotoh (Bocchi)", "BOCCHI THE ROCK!", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b257562-Ru35NYPfsqhY.png"),
        AnimeAvatar(98, "Kyojuro Rengoku", "Demon Slayer", "Demon Slayer", "https://s4.anilist.co/file/anilistcdn/character/large/b129133-VlTPowwt68rJ.png"),
        AnimeAvatar(99, "Yu Nishinoya", "Haikyu!!", "Shonen", "https://s4.anilist.co/file/anilistcdn/character/large/b67327-zQb1dlC7joPb.jpg"),
        AnimeAvatar(100, "Rei Ayanami", "Neon Genesis Evangelion", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/86-cA1zL7fyls8E.jpg"),
        AnimeAvatar(101, "Karma Akabane", "Assassination Classroom", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b71933-HQ1TSjlrJ8Hv.jpg"),
        AnimeAvatar(102, "Roxy Migurdia", "Mushoku Tensei: Jobless Reincarnation", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b88350-QU1iwgZ887U8.png"),
        AnimeAvatar(103, "Yuta Okkotsu", "Jujutsu Kaisen", "Jujutsu Kaisen", "https://s4.anilist.co/file/anilistcdn/character/large/b129571-GHJk7gviHOOw.jpg"),
        AnimeAvatar(104, "Shinji Ikari", "Neon Genesis Evangelion", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b89-ZtZhXkh1rITn.png"),
        AnimeAvatar(105, "Kana Arima", "OSHI NO KO", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b188783-77orwP7vNuNg.png"),
        AnimeAvatar(106, "Sakuta Azusagawa", "Rascal Does Not Dream of Bunny Girl Senpai", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/n127221-Wxg4xFtW4kaJ.png"),
        AnimeAvatar(107, "Kyo Soma", "Fruits Basket (2019)", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b209-NOAbiLvJt1QA.png"),
        AnimeAvatar(108, "Johan Liebert", "Monster", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b719-y984mDWyGf5n.jpg"),
        AnimeAvatar(109, "Misato Katsuragi", "Neon Genesis Evangelion", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b1259-afTQkZ5SVMOn.png"),
        AnimeAvatar(110, "Shouya Ishida", "A Silent Voice", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b80491-NK6pxb6oH61P.png"),
        AnimeAvatar(111, "Ray", "The Promised Neverland", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b121724-SJTdODjeO7e6.jpg"),
        AnimeAvatar(112, "Ai Hayasaka", "Kaguya-sama", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b121104-7TYRl3EEsDYU.png"),
        AnimeAvatar(113, "Nino Nakano", "The Quintessential Quintuplets", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b126372-DtorHRgQaYUJ.png"),
        AnimeAvatar(114, "Yami Sukehiro", "Black Clover", "Shonen", "https://s4.anilist.co/file/anilistcdn/character/large/b124440-Lpdo6y8cljV6.png"),
        AnimeAvatar(115, "C.C.", "Code Geass", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b1111-UhmlFtRFrnWa.png"),
        AnimeAvatar(116, "Kenma Kozume", "Haikyu!!", "Shonen", "https://s4.anilist.co/file/anilistcdn/character/large/b71267-q44J2MXMinXD.jpg"),
        AnimeAvatar(117, "Asuna", "Sword Art Online", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b36828-j5ib0adAzGMx.png"),
        AnimeAvatar(118, "Toge Inumaki", "Jujutsu Kaisen", "Jujutsu Kaisen", "https://s4.anilist.co/file/anilistcdn/character/large/b157115-kdhRYQdVhH95.png"),
        AnimeAvatar(119, "Ash Lynx", "BANANA FISH", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b13580-1J7PwIB8kTpu.png"),
        AnimeAvatar(120, "Manjiro Sano (Mikey)", "Tokyo Revengers", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b145341-CuPldCLZMvvf.png"),
        AnimeAvatar(121, "Tooru Oikawa", "Haikyu!!", "Shonen", "https://s4.anilist.co/file/anilistcdn/character/large/b71611-cUZwVfzeNXD9.png"),
        AnimeAvatar(122, "Koro-sensei", "Assassination Classroom", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b65643-jimrOw0RGtoB.png"),
        AnimeAvatar(123, "Chrollo Lucilfer", "Hunter x Hunter", "Hunter x Hunter", "https://s4.anilist.co/file/anilistcdn/character/large/b58-USOmsz3nursi.jpg"),
        AnimeAvatar(124, "Loid Forger", "SPY x FAMILY", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b138101-7NCB0Md8zA6G.png"),
        AnimeAvatar(125, "Trafalgar Law", "One Piece", "One Piece", "https://s4.anilist.co/file/anilistcdn/character/large/b13767-U604OJN9dxCn.jpg"),
        AnimeAvatar(126, "Reze", "Chainsaw Man", "Chainsaw Man", "https://s4.anilist.co/file/anilistcdn/character/large/b148740-ceAibPxLW8rR.png"),
        AnimeAvatar(127, "Yukino Yukinoshita", "My Teen Romantic Comedy SNAFU", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b67067-gqhgjlni0Bcf.png"),
        AnimeAvatar(128, "Nami", "One Piece", "One Piece", "https://s4.anilist.co/file/anilistcdn/character/large/b723-vp5hPptgnNEC.png"),
        AnimeAvatar(129, "Gyro Zeppeli", "JoJo's Bizarre Adventure", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b11772-p7MO37Mk0f5g.png"),
        AnimeAvatar(130, "Vladilena Milizé", "86 EIGHTY-SIX", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b141061-jqIhB9jmClQ3.png"),
        AnimeAvatar(131, "Phosphophyllite", "Land of the Lustrous", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b123385-ild8gXk13xcO.png"),
        AnimeAvatar(132, "DIO", "JoJo's Bizarre Adventure", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b4004-w0OtWuvjhftG.png"),
        AnimeAvatar(133, "Kaori Miyazono", "Your lie in April", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b69411-lxM0FRvWHqlv.png"),
        AnimeAvatar(134, "Kurena Kukumila", "86 EIGHTY-SIX", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b174873-FNf08aPYTVXY.jpg"),
        AnimeAvatar(135, "Shinobu Kocho", "Demon Slayer", "Demon Slayer", "https://s4.anilist.co/file/anilistcdn/character/large/b136070-MC9LLxJsHyHE.png"),
        AnimeAvatar(136, "Asta", "Black Clover", "Shonen", "https://s4.anilist.co/file/anilistcdn/character/large/b123285-tKijiuQErDS0.png"),
        AnimeAvatar(137, "Son Goku", "Dragon Ball Z", "Dragon Ball", "https://s4.anilist.co/file/anilistcdn/character/large/246-wsRRr6z1kii8.png"),
        AnimeAvatar(138, "Shota Aizawa", "My Hero Academia", "My Hero Academia", "https://s4.anilist.co/file/anilistcdn/character/large/b89225-XBgvUhI9naVI.png"),
        AnimeAvatar(139, "Kazuma Satou", "KonoSuba", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b89364-7Th8Tv1XKJtt.png"),
        AnimeAvatar(140, "Musashi Miyamoto", "", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b6194-HOyr8E7FCFHJ.png"),
        AnimeAvatar(141, "Yumeko Jabami", "Kakegurui", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b121889-ABsurpy5SjOW.png"),
        AnimeAvatar(142, "Mami Nanami", "Rent-a-Girlfriend", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b154224-7dJ09BKEnG3v.png"),
        AnimeAvatar(143, "Gabi Braun", "Attack on Titan", "Attack on Titan", "https://s4.anilist.co/file/anilistcdn/character/large/b125659-O37MZQWibV7g.png"),
        AnimeAvatar(144, "Meruem", "Hunter x Hunter", "Hunter x Hunter", "https://s4.anilist.co/file/anilistcdn/character/large/b23277-EYmIxzL64Mji.png"),
        AnimeAvatar(145, "Hanako", "Toilet-bound Hanako-kun", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b128651-GaZImkP2Of1R.png"),
        AnimeAvatar(146, "Miyuki Shirogane", "Kaguya-sama", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b121101-Q8HzKP15At2d.png"),
        AnimeAvatar(147, "Kirito (Kazuto)", "Sword Art Online", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b36765-BnLbXg0Tzzh9.png"),
        AnimeAvatar(148, "Tooru Honda", "Fruits Basket (2019)", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b207-RQ4EUdTD0K62.png"),
        AnimeAvatar(149, "Kamina", "Gurren Lagann", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b2075-sWb5Xz76JWdX.png"),
        AnimeAvatar(150, "Taiga Aisaka", "Toradora!", "Classics & Others", "https://s4.anilist.co/file/anilistcdn/character/large/b12064-7PDN3ylIeAZn.png"),
    )

    fun getAvatarForUsername(username: String): AnimeAvatar {
        if (avatars.isEmpty()) {
            return AnimeAvatar(1, "Monkey D. Luffy", "One Piece", "One Piece", "https://s4.anilist.co/file/anilistcdn/character/large/b40-MNypXsxSRb1R.png")
        }
        val cleanName = username.trim().lowercase()
        val hash = if (cleanName.isBlank()) 0 else kotlin.math.abs(cleanName.hashCode())
        val index = hash % avatars.size
        return avatars[index]
    }
}
